service: brave-clojure

provider:
  name: aws
  runtime: java8
  region: eu-central-1
  stage: ${opt:stage, "dev"}
  memorySize: 1024
  timeout: 60  # 1min

package:
  artifact: target/standalone.jar

functions:
  chapter3:
    handler: brave_clojure.chapter3::handler

  chapter4:
    handler: brave_clojure.chapter4::handler

resources:
  Resources:
    Func1LogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        RetentionInDays: "30"
    Func2LogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        RetentionInDays: "30"

